tasks:
  - init: yarn
    command: yarn dev
  - command: echo 'export PATH="/workspace/solana-release/bin:$PATH"' >> ~/.bashrc

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - jpoissonnier.vscode-styled-components
